### ISSUE TITLE
Flickering header

### ISSUE THREAD

**Issue by MariusSchiffer** [flysofast/lunch-time#1]
The sticky header is flickering between the full-size and the small one at least on Firefox Desktop 69 and Firefox Preview on Android if you do not immediately scroll way past it. Also happens on Chrome, but less frequent.

Would it be possible to remove this feature or add a hysteresis? (As changing the height changes scrollTop again).

PR #2

**Comment by flysofast** [comment]
Thank you for the fix! Safari on iOS and macOS somehow didn't have this problem. 
Merged and published.
